### ISSUE TITLE
500 error notifying subscribers

### ISSUE THREAD

**Issue by btaitelb** [rails-school/school#180]
When I tried to notify subscribers about a recently created lesson ( https://www.railsschool.org/l/mean-testing ), I got a 500 internal server error and the following was in the logs. The emails did go out as far as I can tell, but the tweet did not.

```
2015-07-15T15:22:05.660434+00:00 heroku[router]: at=info method=POST path="/notify_subscribers/260" host=www.railsschool.org request_id=81979c0e-d4ce-446b-b271-5c76756e29c3 fwd="2601:5c2:2:6500:fa16:54ff:fe7d:60b8,108.162.219.148" dyno=web.1 connect=0ms service=1714ms status=500 bytes=906
2015-07-15T15:22:05.639227+00:00 app[web.1]: PG::UndefinedTable: ERROR:  relation "device_tokens" does not exist
2015-07-15T15:22:05.639234+00:00 app[web.1]: LINE 1: SELECT "device_tokens".* FROM "device_tokens"
2015-07-15T15:22:05.639236+00:00 app[web.1]:                                       ^
2015-07-15T15:22:05.639238+00:00 app[web.1]: : SELECT "device_tokens".* FROM "device_tokens"
2015-07-15T15:22:05.639660+00:00 app[web.1]: Completed 500 Internal Server Error in 1673ms
2015-07-15T15:22:05.645957+00:00 app[web.1]: 
2015-07-15T15:22:05.645964+00:00 app[web.1]: ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "device_tokens" does not exist
2015-07-15T15:22:05.645966+00:00 app[web.1]: LINE 1: SELECT "device_tokens".* FROM "device_tokens"
2015-07-15T15:22:05.645968+00:00 app[web.1]:                                       ^
2015-07-15T15:22:05.645969+00:00 app[web.1]: : SELECT "device_tokens".* FROM "device_tokens"):
2015-07-15T15:22:05.645971+00:00 app[web.1]:   app/controllers/users_controller.rb:112:in `emit_lesson_notification_on_socket'
2015-07-15T15:22:05.645974+00:00 app[web.1]:   app/controllers/users_controller.rb:45:in `notify_subscribers'
```

**Comment by gkop** [comment]
@acadet would you migrate the db please?

**Comment by acadet** [comment]
I thought it was automatic. It should be ok from now on. I apologise for the inconvenience.
